
name: "AOTP EvalGate"
description: "Run deterministic LLM/RAG evals as a PR check"
author: "AOTP Ventures"
branding: { icon: "check-square", color: "blue" }

inputs:
  config:
    description: "Path to evalgate YAML config"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install EvalGate (local)
      shell: bash
      run: |
        uv venv .action-venv
        source .action-venv/bin/activate
        uv pip install -e .
        echo "$(pwd)/.action-venv/bin" >> $GITHUB_PATH
    - name: Run EvalGate (local)
      shell: bash
      run: |
        evalgate run --config "${{ inputs.config }}"
    - name: Summary
      if: always()
      shell: bash
      run: |
        evalgate report --summary --artifact ./.evalgate/results.json

