name: "AOTP EvalGate"
description: "Run deterministic LLM/RAG evals as a PR check"
author: "AOTP Ventures"
branding: { icon: "check-square", color: "blue" }

inputs:
  config:
    description: "Path to evalgate YAML config"
    required: true
  openai_api_key:
    description: "OpenAI API key for LLM evaluators (optional)"
    required: false
  anthropic_api_key:
    description: "Anthropic API key for LLM evaluators (optional)"
    required: false
  azure_api_key:
    description: "Azure API key for LLM evaluators (optional)"
    required: false
  check_run:
    description: "Create a GitHub check run with results (optional)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Run EvalGate (PyPI)
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
        AZURE_API_KEY: ${{ inputs.azure_api_key }}
      run: |
        uvx --from evalgate[llm] evalgate run --config "${{ inputs.config }}"
    - name: Summary
      if: always()
      shell: bash
      run: |
        args="--summary --artifact ./.evalgate/results.json"
        if [[ "${{ inputs.check_run }}" == "true" ]]; then
          args="$args --check-run"
        fi
        uvx --from evalgate evalgate report $args
    - name: Upload Results Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: evalgate-results
        path: .evalgate/results.json
        retention-days: 30
